#! /usr/bin/env python3
"""Terminal manager WSGI daemon."""

from termgr.config import CONFIG
from termgr.wsgi import APPLICATION


if __name__ == '__main__':
    HOST = CONFIG['wsgi']['host']
    PORT = int(CONFIG['wsgi']['port'])
    APPLICATION.run(host=HOST, port=PORT)
