#! /usr/bin/env python3
"""Terminal checking interface"""

from termgr.config import CONFIG
from termgr.wsgi.check import APPLICATION


if __name__ == '__main__':
    HOST = CONFIG['check']['host']
    PORT = int(CONFIG['check']['port'])
    APPLICATION.run(host=HOST, port=PORT)
