#! /usr/bin/env python3
"""termgr.

  Command line tool to manage HOMEINFO terminals.

  (C) 2015-2016:  HOMEINFO - Digitale Informationssysteme GmbH

  Maintainer:     Richard Neumann <r.neumann@homeinfo.de>


Usage:
    termgr update [<expr>...] [options]
    termgr upgrade [<expr>...] [options]
    termgr (reboot | chkres | unlock) [<expr>...] [options]

Options:
    --help, -h                  Show this screen.
    --version, -V               Show version.
    --verbose, -v               Be gassy.
    --undeployed, -n            Select undeployed terminals.
    --testing, -t               Select only testing terminals.
    --classes=<classes>, -c     Select terminals of the respective classes.
    --oss=<os>, -o              Select terminals of the respective operating
                                systems.
    --user=<user>, -u           Specify user account for SSH connections.
    --noconfirm                 Do not prompt every 10 terminals on reboot.
"""
from getpass import getuser
from logging import INFO, basicConfig, getLogger
from os import geteuid
from sys import exit as exit_

from docopt import docopt

from fancylog import DEFAULT_ANIMATION, TTYAnimation, TTYAnimator
from syslib import script, Parallelization
from terminallib import get_terminals

from termgr.config import LOG_FORMAT
from termgr.ctrl import TerminalsController


LOGGER = getLogger(__file__)
TERMGR_USER = 'termgr'


def parallelize(function, terminals, chunk=None):
    """Returns a parallelization for the respective function."""

    return Parallelization(function, terminals, single=True, chunk=chunk)


def animate(parallelization, template):
    """Returns a respective animation."""

    animation = TTYAnimation(
        template, DEFAULT_ANIMATION.stages, DEFAULT_ANIMATION.end)
    return TTYAnimator(parallelization, animation=animation)


@script
def main(options):
    """Runs the terminal manager."""

    basicConfig(level=INFO, format=LOG_FORMAT)
    chunk = None if options['--noconfirm'] else 10

    if geteuid() == 0:
        LOGGER.error('Refusing to run as root.')
        return 3

    if getuser() != TERMGR_USER:
        LOGGER.error('You must be %s to run %s.', TERMGR_USER, __file__)
        return 2

    deployed = None if options['--undeployed'] else True
    classes = options['--classes'].split(',') if options['--classes'] else None
    oss = options['--oss'].split(',') if options['--oss'] else None
    terminals = get_terminals(
        options['<expr>'], deployed=deployed, testing=options['--testing'],
        classes=classes, oss=oss)

    ctrl = TerminalsController()

    # Perform selected operation.
    if options['update']:
        with parallelize(ctrl.update, terminals) as para:
            with animate(para, 'Updating {}: {}'):
                para.wait()

        for terminal, *_ in para.failures:
            LOGGER.error('Failed to update %s.', terminal)
    elif options['upgrade']:
        with parallelize(ctrl.upgrade, terminals) as para:
            with animate(para, 'Staging {}: {}'):
                para.wait()

        for terminal, *_ in para.failures:
            LOGGER.error('Failed to upgrade %s.', terminal)
    elif options['reboot']:
        with parallelize(ctrl.reboot, terminals, chunk=chunk) as para:
            with animate(para, 'Rebooting {}: {}'):
                para.wait()
    elif options['chkres']:
        with parallelize(ctrl.chkres, terminals) as para:
            with animate(para, 'Checking resolution {}: {}'):
                para.wait()
    elif options['unlock']:
        with parallelize(ctrl.unlock, terminals) as para:
            with animate(para, 'Unlocking {}: {}'):
                para.wait()

        for terminal, *_ in para.failures:
            LOGGER.error('Failed to unlock %s.', terminal)

    return 0


if __name__ == '__main__':
    exit_(main(docopt(__doc__)))
